=== danielhstahl/DEPRICATED-option_price_faas/models/GetConstraintsResponse_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "rate":{
            "lower":{
                "type":"number"
            },
            "upper":{
                "type":"number"
            }
        },
        "asset":{
            "lower":{
                "type":"number"
            },
            "upper":{
                "type":"number"
            }
        },
        "maturity":{
            "lower":{
                "type":"number"
            },
            "upper":{
                "type":"number"
            }
        },
        "num_u":{
            "lower":{
                "type":"number"
            },
            "upper":{
                "type":"number"
            }
        },
        "quantile":{
            "lower":{
                "type":"number"
            },
            "upper":{
                "type":"number"
            }
        },
        "lambda":{
            "lower":{
                "type":"number"
            },
            "upper":{
                "type":"number"
            }
        },
        "mu_l":{
            "lower":{
                "type":"number"
            },
            "upper":{
                "type":"number"
            }
        },
        "sig_l":{
            "lower":{
                "type":"number"
            },
            "upper":{
                "type":"number"
            }
        },
        "c":{
            "lower":{
                "type":"number"
            },
            "upper":{
                "type":"number"
            }
        },
        "g":{
            "lower":{
                "type":"number"
            },
            "upper":{
                "type":"number"
            }
        },
        "m":{
            "lower":{
                "type":"number"
            },
            "upper":{
                "type":"number"
            }
        },
        "y":{
            "lower":{
                "type":"number"
            },
            "upper":{
                "type":"number"
            }
        },
        "v0":{
            "lower":{
                "type":"number"
            },
            "upper":{
                "type":"number"
            }
        },
        "speed":{
            "lower":{
                "type":"number"
            },
            "upper":{
                "type":"number"
            }
        },
        "eta_v":{
            "lower":{
                "type":"number"
            },
            "upper":{
                "type":"number"
            }
        },
        "sigma":{
            "lower":{
                "type":"number"
            },
            "upper":{
                "type":"number"
            }
        },
        "rho":{
            "lower":{
                "type":"number"
            },
            "upper":{
                "type":"number"
            }
        }
    },
    "additionalProperties": false
}

=== danielhstahl/DEPRICATED-option_price_faas/docs/GetConstraintsExampleResponse.json
{
    "rate": {
      "lower": 0,
      "upper": 0
    },
    "asset": {
      "lower": 0,
      "upper": 0
    },
    "maturity": {
      "lower": 0,
      "upper": 0
    },
    "num_u": {
      "lower": 0,
      "upper": 0
    },
    "quantile": {
      "lower": 0,
      "upper": 0
    },
    "lambda": {
      "lower": 0,
      "upper": 0
    },
    "mu_l": {
      "lower": 0,
      "upper": 0
    },
    "sig_l": {
      "lower": 0,
      "upper": 0
    },
    "c": {
      "lower": 0,
      "upper": 0
    },
    "g": {
      "lower": 0,
      "upper": 0
    },
    "m": {
      "lower": 0,
      "upper": 0
    },
    "y": {
      "lower": 0,
      "upper": 0
    },
    "v0": {
      "lower": 0,
      "upper": 0
    },
    "speed": {
      "lower": 0,
      "upper": 0
    },
    "eta_v": {
      "lower": 0,
      "upper": 0
    },
    "sigma": {
      "lower": 0,
      "upper": 0
    },
    "rho": {
      "lower": 0,
      "upper": 0
    }
  }

=== danielhstahl/DEPRICATED-option_price_faas/docs/GetMertonConstraintsExampleResponse.json
{
    "lambda": {
      "lower": 0,
      "upper": 4
    },
    "mu_l": {
      "lower": 0,
      "upper": 1
    },
    "sig_l": {
      "lower": 0,
      "upper": 0.6
    },
    "v0": {
      "lower": 0,
      "upper": 2
    },
    "speed": {
      "lower": 0,
      "upper": 2
    },
    "eta_v": {
      "lower": 0,
      "upper": 0.5
    },
    "sigma": {
      "lower": 0,
      "upper": 1
    },
    "rho": {
      "lower": -1,
      "upper": 1
    }
  }

=== danielhstahl/DEPRICATED-option_price_faas/docs/GetHestonConstraintsExampleResponse.json
{
    "v0": {
      "lower": 0,
      "upper": 0.9,
      "types":"float"
    },
    "speed": {
      "lower": 0,
      "upper": 2,
      "types":"float"
    },
    "eta_v": {
      "lower": 0,
      "upper": 0.5,
      "types":"float"
    },
    "sigma": {
      "lower": 0,
      "upper": 1,
      "types":"float"
    },
    "rho": {
      "lower": -1,
      "upper": 1,
      "types":"float"
    }
}

=== danielhstahl/DEPRICATED-option_price_faas/docs/GetCGMYConstraintsExampleResponse.json
{
    "c":{
        "lower":0,
        "upper":10,
        "type":"float"
    },
    "g":{
        "lower":0,
        "upper":20,
        "type":"float"
    },
    "m":{
        "lower":0,
        "upper":20,
        "type":"float"
    },
    "y":{
        "lower":-2,
        "upper":2,
        "type":"float"
    },
    "v0": {
      "lower": 0,
      "upper": 2,
      "type":"float"
    },
    "speed": {
      "lower": 0,
      "upper": 2,
      "type":"float"
    },
    "eta_v": {
      "lower": 0,
      "upper": 0.5,
      "type":"float"
    },
    "sigma": {
      "lower": 0,
      "upper": 1,
      "type":"float"
    },
    "rho": {
      "lower": -1,
      "upper": 1,
      "type":"float"
    }
  }

=== danielhstahl/DEPRICATED-option_price_faas/docs/GetMarketConstraintsExampleResponse.json
{
    "asset":{
        "lower":0.0,"upper":1000000.0,"types":"float"
    },
    "maturity":{
        "lower":0.0,"upper":1000000.0,"types":"float"
    },
    "num_u":{
        "lower":5.0,"upper":10.0,"types":"int"
    },
    "quantile":{
        "lower":0.0,"upper":1.0,"types":"float"
    },
    "rate":{
        "lower":0.0,"upper":0.4,"types":"float"
    }
}
